# Generated by Django 4.2.6 on 2024-04-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='Category_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.CharField(max_length=255),
        ),
    ]
