# Generated by Django 4.2.6 on 2024-04-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_subcategory_category_name_and_more'),
        ('store', '0003_alter_product_subcategory_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
