# Generated by Django 4.2.6 on 2024-04-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_delete_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Type',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
    ]
